### ISSUE TITLE
Per-World Inventories

### ISSUE THREAD

**Issue by Ender2K89** [Lennord/MultiWorld#2]
It would be cool if you could add something similar to Multiverse-Inventories to this Skript.

**Comment by Lennord** [comment]
> It would be cool if you could add something similar to Multiverse-Inventories to this Skript.

Hello, it's a good idea but I might do it in the future.

**Comment by Ender2K89** [comment]
I really hope you do, this Skript is really cool and I think this would be a very cool feature.

**Comment by Lennord** [comment]
> I really hope you do, this Skript is really cool and I think this would be a very cool feature.

Thank you for your message, I will do it but not right away.

**Comment by Lennord** [comment]
> It would be cool if you could add something similar to Multiverse-Inventories to this Skript.

The per-world inventory system was implemented in the 2.1.0 update.
Update: https://www.spigotmc.org/resources/multiworld-skript-1-17-1-1-19-3.92889/updates
